# -*- coding: utf-8 -*-
"""FAR Panel registro datos_streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tIAzD2-zRQvNO-lhUYdLU2o-y1wRgAJV
"""

!pip install streamlit
# app.py
import os
import pandas as pd
from datetime import datetime
from zoneinfo import ZoneInfo
import streamlit as st

# Ruta del archivo
csv_path = "registro_produccion.csv"

# Inicializar archivo
if not os.path.exists(csv_path):
    df = pd.DataFrame(columns=["FechaHora", "Operario", "Turno", "Producto", "Unidades", "Observaciones"])
    df.to_csv(csv_path, index=False)
else:
    df = pd.read_csv(csv_path)

# Interfaz
st.set_page_config(page_title="Registro de Producción - CEE", layout="centered")
st.title("📦 Registro de Producción - Centro Especial de Empleo")

# Formulario
operario = st.selectbox("👤 Operario", ["Juan", "Lucía", "Carlos", "Otro"])
if operario == "Otro":
    operario = st.text_input("Introduce el nombre del operario")

turno = st.radio("🕒 Turno", ["Mañana", "Tarde", "Noche"])
producto = st.selectbox("🧱 Producto", ["Producto A", "Producto B", "Producto C"])
unidades = st.number_input("🔢 Unidades producidas", min_value=1, step=1)
observaciones = st.text_area("📝 Observaciones", placeholder="Ej. 2 unidades defectuosas")

from datetime import datetime
import pytz

# Registrar
if st.button("✅ Registrar producción"):
    zona = ZoneInfo("Europe/Madrid")
    nueva_fila = {
        "FechaHora": datetime.now(zona).strftime("%Y-%m-%d %H:%M:%S"),
        "Operario": operario,
        "Turno": turno,
        "Producto": producto,
        "Unidades": unidades,
        "Observaciones": observaciones
    }
    df = pd.concat([df, pd.DataFrame([nueva_fila])], ignore_index=True)
    df.to_csv(csv_path, index=False)
    st.success("Registro guardado correctamente.")

# Mostrar últimos registros
st.markdown("### 📋 Últimos registros")
st.dataframe(df.tail(5), use_container_width=True)



# Descargar CSV
with open(csv_path, "rb") as f:
    st.download_button("⬇️ Descargar CSV", f, file_name="registro_produccion.csv", mime="text/csv")

# Eliminar archivo
if st.button("🗑️ Eliminar archivo de producción"):
    os.remove(csv_path)
    st.warning("Archivo eliminado. Recarga la app para reiniciar.")