# -*- coding: utf-8 -*-
"""FAR Panel registro datos_v10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Dv0dBbgJe3tNTQkXsU1031JCAWOpV_K
"""

#!pip install streamlit pandas pytz
# 1. Importar librerías necesarias
import streamlit as st
import pandas as pd
from datetime import datetime
import os
from zoneinfo import ZoneInfo
import json

DATA_FILE = "usuarios.json"

# Cargar datos de usuarios
if os.path.exists(DATA_FILE):
    try:
        with open(DATA_FILE, "r", encoding="utf-8") as f:
            usuarios = json.load(f)
    except json.JSONDecodeError:
        st.error("❌ El archivo de usuarios está dañado o no tiene formato JSON válido.")
        usuarios = {}
else:
    usuarios = {}

# Estado de sesión
if "usuario_logueado" not in st.session_state:
    st.session_state.usuario_logueado = None


def guardar_estados():
    if "usuario_logueado" not in st.session_state:
        return  # No hay usuario activo

    usuario = st.session_state.usuario_logueado
    estados = {
        k: v for k, v in st.session_state.items()
        if k.startswith("estado_linea_")
    }

    ruta_archivo = f"estados_{usuario}.json"
    with open(ruta_archivo, "w") as f:
        json.dump(estados, f)


def cargar_estados():
    if "usuario_logueado" not in st.session_state:
        return  # No hay usuario activo

    usuario = st.session_state.usuario_logueado
    ruta_archivo = f"estados_{usuario}.json"
    if os.path.exists(ruta_archivo):
        with open(ruta_archivo, "r") as f:
            estados_guardados = json.load(f)
        for k, v in estados_guardados.items():
            st.session_state[k] = v

def safe_rerun():
    st.experimental_rerun()

# Mostrar login/registro SOLO si el usuario NO está logueado
if "usuario_logueado" not in st.session_state or not st.session_state.usuario_logueado:
    st.title("🔐 Sistema de producción")
    if "modo" not in st.session_state:
        st.session_state.modo = "Iniciar sesión"  # Valor por defecto
    st.radio("¿Tienes una cuenta?", ["Iniciar sesión", "Registrarse"], key="modo")
    modo = st.session_state.modo
    # Redirigir automáticamente a "Iniciar sesión" tras un registro exitoso
    if st.session_state.get("registro_completado"):
        del st.session_state["registro_completado"]
        st.experimental_rerun()


    if modo == "Iniciar sesión":
        usuario = st.text_input("CEE / Usuario")
        clave = st.text_input("Clave", type="password")

        if st.button("Entrar"):
            if usuario in usuarios and usuarios[usuario]["clave"] == clave:
                st.session_state.usuario_logueado = usuario
                st.success("✅ Sesión iniciada")
                cargar_estados()  # ✅ Importante
                st.session_state.etapa = "linea"  # Avanzar al flujo principal
                st.rerun()
            else:
                st.error("❌ Usuario o clave incorrecta")

    else:  # Registro
        nuevo_usuario = st.text_input("Nuevo CEE / Usuario")
        nueva_clave = st.text_input("Nueva clave", type="password")

        st.markdown("### ➕ Añadir línea(s) de producción")

        lineas_registro = {}
        num_lineas = st.number_input("Número de líneas a registrar", min_value=1, step=1, key="num_lineas_registro")

        for i in range(int(num_lineas)):
            nombre_linea = st.text_input(f"Nombre de la línea {i+1}", key=f"nombre_linea_{i}")
            num_estaciones = st.number_input(f"Número de estaciones para línea {i+1}", min_value=1, step=1, key=f"num_estaciones_{i}")

            estaciones = []
            for j in range(int(num_estaciones)):
                nombre_estacion = st.text_input(f"Nombre estación {j+1} de línea {i+1}", key=f"estacion_{i}_{j}")
                estaciones.append(nombre_estacion)

            lineas_registro[nombre_linea] = {
                "num": num_estaciones,
                "nombres": estaciones
            }

        if st.button("Registrarse"):
            if nuevo_usuario in usuarios:
                st.warning("⚠️ Este CEE ya está registrado")
            elif nuevo_usuario.strip() == "" or nueva_clave.strip() == "":
                st.warning("⚠️ Completa todos los campos de usuario y clave")
            elif any(nombre.strip() == "" for nombre in lineas_registro.keys()):
                st.warning("⚠️ Todos los nombres de línea deben estar completos")
            else:
                usuarios[nuevo_usuario] = {
                    "clave": nueva_clave,
                    "lineas": lineas_registro
                }
                with open(DATA_FILE, "w", encoding="utf-8") as f:
                    json.dump(usuarios, f, indent=4)

                st.success("✅ Registro exitoso. Redirigiendo al inicio de sesión...")
                st.session_state["registro_completado"] = True



# Inicializar variables necesarias para el flujo
if "etapa" not in st.session_state:
    st.session_state.etapa = "inicio" if st.session_state.usuario_logueado else "login"
if "linea" not in st.session_state:
    st.session_state.linea = None
if "estacion" not in st.session_state:
    st.session_state.estacion = None

if "df" not in st.session_state:
    st.session_state.df = pd.DataFrame(columns=[
        "Fecha", "Hora", "CEE", "Línea", "Estación", "Estado",
        "Operario", "Turno", "Producto", "Unidades producidas",
        "Unidades defectuosas", "Observaciones"
    ])

if "csv_path" not in st.session_state and st.session_state.usuario_logueado:
    st.session_state.csv_path = f"registro_{st.session_state.usuario_logueado}.csv"



if "usuario_logueado" in st.session_state and st.session_state.usuario_logueado:
    usuario = st.session_state.usuario_logueado
    lineas_usuario = usuarios.get(usuario, {}).get("lineas", {})

    nuevos_estados = False
    for linea, estaciones in lineas_usuario.items():
        if isinstance(estaciones, dict):
            estaciones = estaciones.get("nombres", [])
        for nombre_estacion in estaciones:
            key_estado = f"estado_linea_{linea}_Estacion_{nombre_estacion}"
            if key_estado not in st.session_state:
                st.session_state[key_estado] = "No iniciada"
                nuevos_estados = True
    if nuevos_estados:
        guardar_estados()


def eliminar_registro_por_indice(indice):
    df = st.session_state.df

    if df.empty:
        st.warning("⚠️ No hay registros para eliminar.")
        return

    if indice not in df.index:
        st.error("❌ Índice inválido. No se puede eliminar el registro.")
        return

    # Extraer datos del registro
    registro = df.loc[indice]
    estado_actual = registro["Estado"]
    linea = registro["Línea"]
    estacion = registro["Estación"]

    # Validar si el registro es de otra estación o línea (cuando es un cambio de estado)
    if estado_actual in ["Parada producción", "Reanudación producción"]:
        if (
            linea != st.session_state.linea or
            str(estacion) != str(st.session_state.estacion)
        ):
            st.warning(
                f"⚠️ No se puede eliminar un registro de estado de otra estación o línea.\n\n"
                f"Registro seleccionado: {linea} - Estación {estacion}\n"
                f"Estás en: {st.session_state.linea} - Estación {st.session_state.estacion}"
            )
            return

    # Clave de estado en el nuevo formato
    key_estado = f"estado_linea_{linea}_Estacion_{estacion}"

    # Eliminar el registro
    df = df.drop(indice).reset_index(drop=True)
    st.session_state.df = df

    # Si se eliminó el último registro
    if indice == len(df):  # ya está reiniciado con reset_index()
        if estado_actual in ["Parada producción", "Reanudación producción"]:
            df_filtrado = df[
                (df["Línea"] == linea) &
                (df["Estación"] == estacion)
            ]
            if not df_filtrado.empty:
                ultimo_estado = df_filtrado.iloc[-1]["Estado"]
                if ultimo_estado == "Reanudación producción":
                    st.session_state[key_estado] = "En producción"
                elif ultimo_estado == "Parada producción":
                    st.session_state[key_estado] = "Parada por incidencia"
                else:
                    st.session_state[key_estado] = "En producción"
            else:
                st.session_state[key_estado] = "No iniciada"
                st.info("ℹ️ Se ha eliminado el último registro. No quedan registros en esa estación.")

            guardar_estados()
            st.session_state.produccion_iniciada = (
                st.session_state[key_estado] == "En producción"
            )

    st.session_state.df.to_csv(st.session_state.csv_path, index=False, sep=';', encoding='utf-8-sig')
    st.success("✅ Registro eliminado correctamente.")
    st.rerun()


if st.session_state.etapa == "linea":
    usuario = st.session_state.usuario_logueado
    lineas = list(usuarios[usuario]["lineas"].keys())
    if not lineas:
        st.warning("⚠️ No tienes líneas definidas. Por favor, añade alguna en la sección anterior.")
    else:
        linea = st.selectbox(f"Selecciona la línea de {usuario}", lineas, index=0, key="select_linea")
        if st.button("Continuar", key="btn_linea"):
            st.session_state.linea = linea
            st.session_state.etapa = "estacion"
            st.rerun()


elif st.session_state.etapa == "estacion":
    usuario = st.session_state.usuario_logueado
    linea = st.session_state.linea

    # Obtener las estaciones de la línea:
    # usuarios[usuario]["lineas"][linea] tiene el número de estaciones,
    # pero convendría almacenar también los nombres (si aún no, habría que modificar el registro de línea para guardar nombres).

    # Suponiendo que guardas nombres en una lista llamada 'nombres_estaciones' dentro del dict línea
    # Ejemplo: usuarios[usuario]["lineas"][linea] = {"num": 3, "nombres": ["Est1", "Est2", "Est3"]}
    # Si no lo tienes así, tendrías que migrar a ese formato.

    # Aquí un ejemplo si tienes solo número:
    num_estaciones = usuarios[usuario]["lineas"][linea] if isinstance(usuarios[usuario]["lineas"][linea], int) else usuarios[usuario]["lineas"][linea].get("num", 0)

    if isinstance(usuarios[usuario]["lineas"][linea], dict):
        nombres_estaciones = usuarios[usuario]["lineas"][linea].get("nombres", [f"Estación {i+1}" for i in range(num_estaciones)])
    else:
        nombres_estaciones = [f"Estación {i+1}" for i in range(num_estaciones)]

    estacion_seleccionada = st.selectbox("Selecciona la estación", nombres_estaciones, index=0, key="select_estacion")
    if st.button("Continuar", key="btn_estacion"):
        st.session_state.estacion = estacion_seleccionada
        st.session_state.etapa = "registro"
        st.rerun()

elif st.session_state.etapa == "registro":
    usuario = st.session_state.usuario_logueado
    linea = st.session_state.linea
    estacion = st.session_state.estacion

    st.subheader(f"Registro en {usuario} / {linea} / {estacion}")

    key_estado = f"estado_linea_{linea}_Estacion_{estacion}"
    if key_estado not in st.session_state:
        st.session_state[key_estado] = "No iniciada"
        guardar_estados()
    if "produccion_iniciada" not in st.session_state:
        st.session_state.produccion_iniciada = False
    if "mostrar_motivo_reanudacion" not in st.session_state:
        st.session_state.mostrar_motivo_reanudacion = False

    # Mostrar estado actual
    estado = st.session_state.get(key_estado, "No iniciada")

    color = "green"  # Color por defecto
    if estado == "Parada por incidencia":
        color = "red"
    elif estado == "No iniciada":
        color = "gray"
    elif estado == "En producción":
        color = "green"

    st.markdown(
        f"""
        <div style='font-weight:bold; margin-bottom:8px;'>🛠️ Estado actual:
            <span style='background-color:#f0f0f0; color:{color}; padding:4px 8px; border-radius:4px; font-family:monospace;'>
                {estado}
            </span>
        </div>
        """,
        unsafe_allow_html=True
    )

    btn_key_iniciar = f"iniciar_{st.session_state.usuario_logueado}_{st.session_state.linea}_{st.session_state.estacion}"
    iniciar_disabled = estado == "En producción"

    if st.button("🟢 Iniciar Producción", disabled=iniciar_disabled, key=btn_key_iniciar):
        if estado == "Parada por incidencia":
            st.session_state.mostrar_motivo_reanudacion = True
        else:
            zona = ZoneInfo("Europe/Madrid")
            fila_inicio = {
                "Fecha": datetime.now(zona).strftime("%Y-%m-%d"),
                "Hora": datetime.now(zona).strftime("%H:%M:%S"),
                "CEE": usuario,
                "Línea": linea,
                "Estación": estacion,
                "Estado": "Inicio producción",
                "Operario": "",
                "Turno": "",
                "Producto": "",
                "Unidades producidas": "",
                "Unidades defectuosas": "",
                "Observaciones": "Inicio de la jornada de producción"
            }
            st.session_state.df = pd.concat([st.session_state.df, pd.DataFrame([fila_inicio])], ignore_index=True)
            st.session_state.df.to_csv(st.session_state.csv_path, index=False, sep=';', encoding='utf-8-sig')

            for linea_actual, data_linea in usuarios[usuario]["lineas"].items():
                nombres_estaciones = data_linea.get("nombres", [])
                for nombre_estacion in nombres_estaciones:
                    key_estado_update = f"estado_linea_{linea_actual}_Estacion_{nombre_estacion}"
                    st.session_state[key_estado_update] = "En producción"

            guardar_estados()
            st.session_state.produccion_iniciada = True

            # 🔄 Re-ejecutar para actualizar el valor de `estado` en pantalla
            st.rerun()


    if st.session_state.mostrar_motivo_reanudacion:
        motivo_reanudacion = st.text_area("📝 Motivo de reanudación de producción")

        if st.button("✅ Registrar reanudación"):
            if motivo_reanudacion.strip() == "":
                st.warning("⚠️ Por favor, introduce un motivo antes de registrar la reanudación.")
            else:
                zona = ZoneInfo("Europe/Madrid")
                fila_reanudacion = {
                    "Fecha": datetime.now(zona).strftime("%Y-%m-%d"),
                    "Hora": datetime.now(zona).strftime("%H:%M:%S"),
                    "CEE": st.session_state.usuario_logueado,
                    "Línea": st.session_state.linea,
                    "Estación": st.session_state.estacion,
                    "Estado": "Reanudación producción",
                    "Operario": "",
                    "Turno": "",
                    "Producto": "",
                    "Unidades producidas": "",
                    "Unidades defectuosas": "",
                    "Observaciones": motivo_reanudacion
                }
                st.session_state.df = pd.concat([st.session_state.df, pd.DataFrame([fila_reanudacion])], ignore_index=True)
                st.session_state.df.to_csv(st.session_state.csv_path, index=False, sep=';', encoding='utf-8-sig')

                st.session_state[key_estado] = "En producción"
                guardar_estados()
                st.session_state.produccion_iniciada = True
                st.session_state.mostrar_motivo_reanudacion = False
                st.success("✅ Producción reanudada correctamente.")
                st.rerun()



    # Inicializa el estado si no existe aún
    if "mostrar_motivo_parada" not in st.session_state:
        st.session_state.mostrar_motivo_parada = False

    btn_key_parada = f"parada_{st.session_state.usuario_logueado}_{st.session_state.linea}_{st.session_state.estacion}"
    parada_disabled = st.session_state[key_estado] in ["Parada por incidencia", "No iniciada"]

    # Paso 1: Pulsar botón de parada
    if st.button("⛔ Parada por incidencia", disabled=parada_disabled, key=btn_key_parada):
        st.session_state.mostrar_motivo_parada = True

    # Paso 2: Mostrar cuadro de texto solo si se ha pulsado el botón
    if st.session_state.mostrar_motivo_parada:
        motivo = st.text_area("📝 Introduce el motivo de la parada")

        if st.button("Registrar parada con motivo"):
            if motivo.strip() == "":
                st.warning("⚠️ Por favor, introduce un motivo antes de registrar la parada.")
            else:
                zona = ZoneInfo("Europe/Madrid")
                fila_parada = {
                    "Fecha": datetime.now(zona).strftime("%Y-%m-%d"),
                    "Hora": datetime.now(zona).strftime("%H:%M:%S"),
                    "CEE": st.session_state.usuario_logueado,
                    "Línea": st.session_state.linea,
                    "Estación": st.session_state.estacion,
                    "Estado": "Parada producción",
                    "Operario": "",
                    "Turno": "",
                    "Producto": "",
                    "Unidades producidas": "",
                    "Unidades defectuosas": "",
                    "Observaciones": motivo
                }
                st.session_state.df = pd.concat([st.session_state.df, pd.DataFrame([fila_parada])], ignore_index=True)
                st.session_state.df.to_csv(st.session_state.csv_path, index=False, sep=';', encoding='utf-8-sig')
                st.session_state[key_estado] = "Parada por incidencia"
                guardar_estados()  # <-- GUARDAR CAMBIOS
                st.session_state.produccion_iniciada = False
                st.success("✅ Parada registrada correctamente.")
                st.session_state.mostrar_motivo_parada = False  # Ocultar cuadro de texto
                st.rerun()


    btn_key_finalizar = f"finalizar_{st.session_state.usuario_logueado}_{st.session_state.linea}_{st.session_state.estacion}"
    finalizar_disabled = st.session_state[key_estado] == "No iniciada"

    if st.button("🏁 Finalizar jornada", disabled=finalizar_disabled, key=btn_key_finalizar):
        zona = ZoneInfo("Europe/Madrid")
        fila_fin = {
            "Fecha": datetime.now(zona).strftime("%Y-%m-%d"),
            "Hora": datetime.now(zona).strftime("%H:%M:%S"),
            "CEE": st.session_state.usuario_logueado,
            "Línea": st.session_state.linea,
            "Estación": st.session_state.estacion,
            "Estado": "Fin producción",
            "Operario": "",
            "Turno": "",
            "Producto": "",
            "Unidades producidas": "",
            "Unidades defectuosas": "",
            "Observaciones": "Fin de la jornada de producción"
        }
        st.session_state.df = pd.concat([st.session_state.df, pd.DataFrame([fila_fin])], ignore_index=True)
        st.session_state.df.to_csv(st.session_state.csv_path, index=False, sep=';', encoding='utf-8-sig')

        # Establecer "No iniciada" en todas las estaciones al finalizar jornada
        for linea_actual, data_linea in usuarios[usuario]["lineas"].items():
            nombres_estaciones = data_linea.get("nombres", [])
            for nombre_estacion in nombres_estaciones:
                key_estado_update = f"estado_linea_{linea_actual}_Estacion_{nombre_estacion}"
                st.session_state[key_estado_update] = "No iniciada"

        guardar_estados()  # <-- GUARDAR CAMBIOS
        st.session_state.mostrar_motivo_parada = False  # Asegura que no se muestre texto de parada
        st.success("✅ Jornada finalizada correctamente.")
        st.rerun()

    # Si la producción está iniciada, mostrar formulario
    if st.session_state[key_estado] == "En producción":
        st.markdown("### 🧾 Registrar producción")
        operario = st.text_input("👤 Operario")
        turno = st.radio("🕒 Turno", ["Mañana", "Tarde", "Noche"])
        producto = st.selectbox("🧱 Producto", ["Producto A", "Producto B", "Producto C"])
        unidades_producidas = st.number_input("🔢 Unidades producidas", min_value=1, step=1)
        unidades_defectuosas = st.number_input("❌ Unidades defectuosas", min_value=0, step=1)
        observaciones = st.text_area("📝 Observaciones")

        if st.button("✅ Registrar producción"):
            zona = ZoneInfo("Europe/Madrid")
            nueva_fila = {
                "Fecha": datetime.now(zona).strftime("%Y-%m-%d"),
                "Hora": datetime.now(zona).strftime("%H:%M:%S"),
                "CEE": st.session_state.usuario_logueado,  # <-- Cambio aquí
                "Línea": st.session_state.linea,
                "Estación": st.session_state.estacion,
                "Estado": st.session_state[key_estado],
                "Operario": operario,
                "Turno": turno,
                "Producto": producto,
                "Unidades producidas": unidades_producidas,
                "Unidades defectuosas": unidades_defectuosas,
                "Observaciones": observaciones
            }
            st.session_state.df = pd.concat([st.session_state.df, pd.DataFrame([nueva_fila])], ignore_index=True)
            st.session_state.df.to_csv(st.session_state.csv_path, index=False, sep=';', encoding='utf-8-sig')
            st.success("✅ Registro guardado correctamente.")
    else:
        st.warning("⚠️ Debes iniciar la producción antes de poder registrar unidades.")

    # Mostrar últimos registros
    st.markdown("---")
    st.markdown("### 📋 Últimos registros")
    st.dataframe(st.session_state.df.tail(5), use_container_width=True)



# --- BOTONES DE NAVEGACIÓN Y EDICIÓN SEGÚN LA ETAPA ---

if st.session_state.etapa == "linea":
    st.markdown("---")
    if st.button("🔙 Volver al inicio"):
        st.session_state.etapa = "CEE"
        # Limpia variables que dependen de la selección previa
        st.session_state.pop("csv_path", None)
        st.session_state.pop("usuario_logueado", None)  # <-- cambio aquí
        st.session_state.pop("linea", None)
        st.session_state.pop("estacion", None)
        st.session_state.pop("df", None)
        st.session_state.pop("produccion_iniciada", None)
        st.rerun()  # <--- Añadido

elif st.session_state.etapa == "estacion":
    st.markdown("---")
    col1, col2 = st.columns(2)
    with col1:
        if st.button("🔁 Cambiar línea"):
            st.session_state.etapa = "linea"
            st.rerun()
    with col2:
        if st.button("🔙 Volver al inicio"):
            st.session_state.etapa = "CEE"
            # Limpia variables que dependen de la selección previa
            st.session_state.pop("csv_path", None)
            st.session_state.pop("usuario_logueado", None)  # <-- cambio aquí
            st.session_state.pop("linea", None)
            st.session_state.pop("estacion", None)
            st.session_state.pop("df", None)
            st.session_state.pop("produccion_iniciada", None)
            st.rerun()  # <--- Añadido

elif st.session_state.etapa == "registro":
    # Descargar CSV
    if "csv_path" in st.session_state and os.path.exists(st.session_state.csv_path):
        with open(st.session_state.csv_path, "rb") as f:
            st.download_button(
                "⬇️ Descargar CSV",
                f,
                file_name=f"registro_produccion_{st.session_state.usuario_logueado}.csv",  # <-- cambio aquí
                mime="text/csv"
            )

    # --- Botón para mostrar/ocultar edición de registros ---
    if "mostrar_edicion" not in st.session_state:
        st.session_state.mostrar_edicion = False

    if st.button("✏️ Modificar o eliminar un registro"):
        # Verifica si hay registros
        if st.session_state.df.empty:
            st.warning("⚠️ Aún no hay registros disponibles para modificar o eliminar.")
            st.session_state.mostrar_edicion = False
        else:
            st.session_state.mostrar_edicion = not st.session_state.mostrar_edicion

    if st.session_state.mostrar_edicion:
        st.markdown("### ✏️ Selecciona un registro reciente")

        ultimos_registros = st.session_state.df.tail(5).reset_index(drop=True)

        def formatear_registro(row):
            # Aquí puedes dejar el campo 'CEE' para mostrar el usuario/logueado/CEE actual
            return f"{row['Fecha']} - {row['Hora']} - {row['CEE']} - {row['Línea']} - {row['Estación']} - {row['Estado']} - {row['Operario']} - {row['Turno']} - {row['Producto']} - {row['Unidades producidas']} - {row['Unidades defectuosas']} - {row['Observaciones']}"

        opciones = [(i, formatear_registro(row)) for i, row in ultimos_registros.iterrows()]
        opciones_dict = {desc: idx for idx, desc in opciones}

        registro_str = st.selectbox("Selecciona un registro", list(opciones_dict.keys()), key="registro_selectbox")
        registro_seleccionado = opciones_dict[registro_str]
        registro = ultimos_registros.loc[registro_seleccionado]

        clave_registro = f"registro_{registro_seleccionado}"

        if registro["Estado"] not in ["Reanudación producción", "Parada producción"]:
            nuevo_operario = st.text_input("👤 Operario", value=registro["Operario"], key=f"operario_{clave_registro}")
            turnos_validos = ["Mañana", "Tarde", "Noche"]
            turno_actual = registro.get("Turno", "")
            if turno_actual in turnos_validos:
                nuevo_turno = st.radio("🕒 Turno", turnos_validos, index=turnos_validos.index(turno_actual), key=f"turno_{clave_registro}")
            else:
                nuevo_turno = st.radio("🕒 Turno", turnos_validos, key=f"turno_{clave_registro}")

            productos_disponibles = ["Producto A", "Producto B", "Producto C"]
            producto_actual = registro.get("Producto", "")

            if producto_actual in productos_disponibles:
                index_producto = productos_disponibles.index(producto_actual)
            else:
                index_producto = 0

            nuevo_producto = st.selectbox("🧱 Producto", productos_disponibles, index=index_producto, key=f"producto_{clave_registro}")

            try:
                valor_producidas = int(registro.get("Unidades producidas", 0))
            except (ValueError, TypeError):
                valor_producidas = 0

            nuevas_producidas = st.number_input("🔢 Unidades producidas", min_value=0, value=valor_producidas, step=1)

            try:
                valor_defectuosas = int(registro.get("Unidades defectuosas", 0))
            except (ValueError, TypeError):
                valor_defectuosas = 0

            nuevas_defectuosas = st.number_input("❌ Unidades defectuosas", min_value=0, value=valor_defectuosas, step=1, key=f"defectuosas_{clave_registro}")
            nuevas_observaciones = st.text_area("📝 Observaciones", value=registro["Observaciones"], key=f"observaciones_{clave_registro}")

            if st.button("💾 Guardar cambios en el registro seleccionado", key=f"guardar_{clave_registro}"):
                index_original = st.session_state.df.tail(5).index[registro_seleccionado]
                st.session_state.df.at[index_original, "Operario"] = nuevo_operario
                st.session_state.df.at[index_original, "Turno"] = nuevo_turno
                st.session_state.df.at[index_original, "Producto"] = nuevo_producto
                st.session_state.df.at[index_original, "Unidades producidas"] = nuevas_producidas
                st.session_state.df.at[index_original, "Unidades defectuosas"] = nuevas_defectuosas
                st.session_state.df.at[index_original, "Observaciones"] = nuevas_observaciones
                st.session_state.df.to_csv(st.session_state.csv_path, index=False, sep=';', encoding='utf-8-sig')
                st.success("✅ Registro modificado correctamente.")
                st.rerun()
        else:
            st.info("🛠 Este registro es de inicio o parada de producción, solo puede eliminarse.")

        if st.button("🗑️ Eliminar registro seleccionado", key=f"eliminar_{clave_registro}"):
            index_original = st.session_state.df.tail(5).index[registro_seleccionado]
            eliminar_registro_por_indice(index_original)


    # Eliminar archivo
    if st.button("🗑️ Eliminar archivo de producción"):
        if os.path.exists(st.session_state.csv_path):
            os.remove(st.session_state.csv_path)
            st.warning(f"Archivo `{st.session_state.csv_path}` eliminado. Recarga la app para reiniciar.")
        else:
            st.warning("⚠️ No se encontró el archivo para eliminar.")

    # --- Botones de navegación al final ---
    st.markdown("---")
    col1, col2, col3 = st.columns(3)

    with col1:
        if st.button("🔁 Cambiar estación"):
            st.session_state.etapa = "estacion"
            st.rerun()

    with col2:
        if st.button("🔁 Cambiar línea"):
            st.session_state.etapa = "linea"
            st.rerun()

    with col3:
        if st.button("🔙 Volver al inicio"):
            st.session_state.etapa = "CEE"
            # Limpia variables que dependen de la selección previa
            st.session_state.pop("csv_path", None)
            st.session_state.pop("usuario_logueado", None)  # <-- Cambiado de 'cee'
            st.session_state.pop("linea", None)
            st.session_state.pop("estacion", None)
            st.session_state.pop("df", None)
            st.session_state.pop("produccion_iniciada", None)
            st.rerun()  # <--- Añadido